/*
* generated by Xtext
*/
package com.versionone.sdk.v1query;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class QueryUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.versionone.sdk.v1query.ui.internal.QueryActivator.getInstance().getInjector("com.versionone.sdk.v1query.Query");
	}
	
}
