/*
 * generated by Xtext
 */
package com.versionone.sdk.v1query;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QueryRuntimeModule extends com.versionone.sdk.v1query.AbstractQueryRuntimeModule {

}
