/*
 * generated by Xtext
 */
package com.versionone.sdk.v1query.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class QueryUiModule extends com.versionone.sdk.v1query.ui.AbstractQueryUiModule {
	public QueryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
