/*
* generated by Xtext
*/
package com.versionone.sdk.v1query.ui.contentassist;

import com.versionone.sdk.v1query.ui.contentassist.AbstractQueryProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class QueryProposalProvider extends AbstractQueryProposalProvider {

}
